services:
  mongo:
    image: mongo:7.0.5
    volumes:
      - type: bind
        source: ./data/mongo
        target: /data/db
    environment:
      MONGO_INITDB_DATABASE: 'mastocord'
    restart: always
  rabbit:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
      LOG_LEVEL: WARN
    restart: always
  mastodon:
    environment:
      MASTODON_BASE_URL: "${MASTODON_BASE_URL}"
      MASTODON_ACCESS_TOKEN: "${MASTODON_ACCESS_TOKEN}"
    build: ./mastodon
    command: python -u ./app.py
    depends_on:
      - mongo
      - rabbit
    restart: always
  discord:
    environment:
      DISCORD_TOKEN: "$DISCORD_TOKEN"
      DISCORD_SNOOPER_CHANNEL_NAME: "$DISCORD_SNOOPER_CHANNEL_NAME"
      LOG_LEVEL: INFO
    build: ./discord
    command: python -u ./app.py
    depends_on:
      - mongo
      - rabbit
    restart: always
